{% set name = "icclim" %}
{% set version = "5.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/icclim-{{ version }}.tar.gz
  sha256: 56799bd9c7ab9ef80aaf3cc969428edf81e67a1d367a4ea2ec0621e6de19c830

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - cftime
    - dask
    - netCDF4
    - numpy
    - pyyaml
    - xarray
    - xclim >=0.34
    - rechunker >=0.5
    - psutil
    - fsspec

test:
  requires:
    - pip
  imports:
    - icclim
    - icclim.models
  commands:
    - pip check

about:
  summary: 'icclim (Index Calculation CLIMate) is a python library for climate indices calculation.'
  home: https://github.com/cerfacs-globc/icclim
  doc_url: https://icclim.readthedocs.io/
  dev_url: https://github.com/cerfacs-globc/icclim
  license: Apache-2.0
  license_file: LICENSE
  description: |
    icclim (Index Calculation CLIMate) is a python library for climate indices calculation.
    It wraps xclim, xarray and dask in a staight forward API. It is first meant to compute
    the ECA&D indices but also provide an API to create customized indices based on a few operators.

extra:
  recipe-maintainers:
    - pagecp
    - bzah
